name: api
on:
  push:
    # branches: [develop]
    paths:
      - ".github/workflows/image.yaml"
      - "!**.md"
  # pull_request:
  #   paths:
  #     - "app/**"
jobs:
  api:
    runs-on: [self-hosted]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: pratikimprowise/squid
          tags: |
            type=raw,value={{branch}}-{{sha}}-{{date 'X'}}
            type=raw,value=5.1-{{sha}}
            type=raw,value=5.1
            type=raw,value=5


      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          push: true
